export const CarData = [
  {
    name: "Mini",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "Sedan",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "Prime Sedan",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "SUV",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "Prime SUV",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "Omni",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "EECO",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
  {
    name: "Bike",
    seater: "4+1 Seater",
    image: "./Sedan 1.png",
    estimate: "6.1 km",
    fare: "₹76",
    extra: "₹18.05",
    price: "₹1",
    rfare: "₹55.95",
    fee: "₹4.75",
    gst: "₹5",
    promo: "APPLIED",
    discount: "₹30",
    total: "₹142",
    count: "1",
  },
];
